--- #YAML:1.0
name:               Math-Aronson
version:            5
abstract:           Generate Aronson's sequence.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lingua::EN::Numbers:  1.01
    Lingua::FR::Numbers:  0.04
    perl:                 5.004
resources:
    homepage:  http://user42.tuxfamily.org/math-aronson/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Lingua::ES::Numeros:  0
            PerlIO::locale:       0.06
            Smart::Comments:      0
            Unicode::CharName:    0
            Unicode::Normalize:   0
            warnings::unused:     0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            File::Spec:          0
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::Synopsis:      0
            Test::Weaken:        3
            Test::YAML::Meta:    0.15
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
recommends:
    Lingua::Any::Numbers:  0.21
    Unicode::Normalize:   0
